-- MySQL Workbench Synchronization
-- Generated: 2016-06-23 13:30
-- Model: CMDB
-- Version: 1.0
-- Project: CMedicinae
-- Author: rafaelgs
-- Banco de dados do sistema CMedicinae

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `cmdb`.`MEDICOS` (
  `COD_MEDICOS` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`COD_MEDICOS`),
  UNIQUE INDEX `COD_MEDICOS_UNIQUE` (`COD_MEDICOS` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cmdb`.`PACIENTES` (
  `COD_PACIENTES` INT(11) NOT NULL AUTO_INCREMENT,
  `CONVENIOS_COD_CONVENIOS` INT(11) NOT NULL,
  PRIMARY KEY (`COD_PACIENTES`, `CONVENIOS_COD_CONVENIOS`),
  UNIQUE INDEX `COD_PACIENTES_UNIQUE` (`COD_PACIENTES` ASC),
  INDEX `fk_PACIENTES_CONVENIOS1_idx` (`CONVENIOS_COD_CONVENIOS` ASC),
  CONSTRAINT `fk_PACIENTES_CONVENIOS1`
    FOREIGN KEY (`CONVENIOS_COD_CONVENIOS`)
    REFERENCES `cmdb`.`CONVENIOS` (`COD_CONVENIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cmdb`.`AGENDAMENTOS` (
  `COD_AGENDAMENTOS` INT(11) NOT NULL AUTO_INCREMENT,
  `MEDICOS_COD_MEDICOS` INT(11) NOT NULL,
  `PACIENTES_COD_PACIENTES` INT(11) NOT NULL,
  PRIMARY KEY (`COD_AGENDAMENTOS`, `MEDICOS_COD_MEDICOS`, `PACIENTES_COD_PACIENTES`),
  INDEX `fk_MEDICOS_has_PACIENTES_PACIENTES1_idx` (`PACIENTES_COD_PACIENTES` ASC),
  INDEX `fk_MEDICOS_has_PACIENTES_MEDICOS_idx` (`MEDICOS_COD_MEDICOS` ASC),
  CONSTRAINT `fk_MEDICOS_has_PACIENTES_MEDICOS`
    FOREIGN KEY (`MEDICOS_COD_MEDICOS`)
    REFERENCES `cmdb`.`MEDICOS` (`COD_MEDICOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDICOS_has_PACIENTES_PACIENTES1`
    FOREIGN KEY (`PACIENTES_COD_PACIENTES`)
    REFERENCES `cmdb`.`PACIENTES` (`COD_PACIENTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cmdb`.`CONVENIOS` (
  `COD_CONVENIOS` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`COD_CONVENIOS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
